package graphql.gitlab.model;

import java.util.Objects;

import org.eclipse.microprofile.graphql.Name;

/**
 * Autogenerated input type of BoardListCreate
 */
@Name("BoardListCreateInput")
public class BoardListCreateInput {

    /**
     * Create the backlog list.
     */
    private Boolean backlog;

    /**
     * Global ID of an existing label.
     */
    private LabelID labelId;

    /**
     * Global ID of the issue board to mutate.
     */
    private BoardID boardId;

    /**
     * Position of the list.
     */
    private Integer position;

    /**
     * Global ID of an existing milestone.
     */
    private MilestoneID milestoneId;

    /**
     * Global ID of an existing iteration.
     */
    private IterationID iterationId;

    /**
     * Global ID of an existing user.
     */
    private UserID assigneeId;

    public Boolean getBacklog() {
        return backlog;
    }

    public BoardListCreateInput setBacklog(Boolean backlog) {
        this.backlog = backlog;
        return this;
    }

    public LabelID getLabelId() {
        return labelId;
    }

    public BoardListCreateInput setLabelId(LabelID labelId) {
        this.labelId = labelId;
        return this;
    }

    public BoardID getBoardId() {
        return boardId;
    }

    public BoardListCreateInput setBoardId(BoardID boardId) {
        this.boardId = boardId;
        return this;
    }

    public Integer getPosition() {
        return position;
    }

    public BoardListCreateInput setPosition(Integer position) {
        this.position = position;
        return this;
    }

    public MilestoneID getMilestoneId() {
        return milestoneId;
    }

    public BoardListCreateInput setMilestoneId(MilestoneID milestoneId) {
        this.milestoneId = milestoneId;
        return this;
    }

    public IterationID getIterationId() {
        return iterationId;
    }

    public BoardListCreateInput setIterationId(IterationID iterationId) {
        this.iterationId = iterationId;
        return this;
    }

    public UserID getAssigneeId() {
        return assigneeId;
    }

    public BoardListCreateInput setAssigneeId(UserID assigneeId) {
        this.assigneeId = assigneeId;
        return this;
    }

    @Override
    public int hashCode() {
        return Objects.hash(backlog, labelId, boardId, position, milestoneId, iterationId, assigneeId);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        BoardListCreateInput other = (BoardListCreateInput) obj;
        return Objects.equals(backlog, other.backlog) && Objects.equals(labelId, other.labelId) && Objects.equals(boardId, other.boardId) && Objects.equals(position, other.position) && Objects.equals(milestoneId, other.milestoneId) && Objects.equals(iterationId, other.iterationId) && Objects.equals(assigneeId, other.assigneeId);
    }

    @Override
    public String toString() {
        return "BoardListCreateInput [backlog=" + backlog + ", labelId=" + labelId + ", boardId=" + boardId + ", position=" + position + ", milestoneId=" + milestoneId + ", iterationId=" + iterationId + ", assigneeId=" + assigneeId + "]";
    }

}
