package graphql.gitlab.model;

import java.util.List;
import java.util.Objects;

import org.eclipse.microprofile.graphql.Name;

/**
 * Autogenerated return type of BoardListCreate.
 */
@Name("BoardListCreatePayload")
public class BoardListCreatePayload {

    /**
     * Errors encountered during execution of the mutation.
     */
    private List<String> errors;

    /**
     * Issue list in the issue board.
     */
    private BoardList list;

    public List<String> getErrors() {
        return errors;
    }

    public BoardListCreatePayload setErrors(List<String> errors) {
        this.errors = errors;
        return this;
    }

    public BoardList getList() {
        return list;
    }

    public BoardListCreatePayload setList(BoardList list) {
        this.list = list;
        return this;
    }

    @Override
    public int hashCode() {
        return Objects.hash(errors, list);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        BoardListCreatePayload other = (BoardListCreatePayload) obj;
        return Objects.equals(errors, other.errors) && Objects.equals(list, other.list);
    }

    @Override
    public String toString() {
        return "BoardListCreatePayload [errors=" + errors + ", list=" + list + "]";
    }

}
