package graphql.gitlab.model;

import java.util.Objects;

import org.eclipse.microprofile.graphql.Name;

/**
 * Autogenerated input type of DestroyEpicBoard
 */
@Name("DestroyEpicBoardInput")
public class DestroyEpicBoardInput {

    /**
     * Global ID of the board to destroy.
     */
    private BoardsEpicBoardID id;

    public BoardsEpicBoardID getId() {
        return id;
    }

    public DestroyEpicBoardInput setId(BoardsEpicBoardID id) {
        this.id = id;
        return this;
    }

    @Override
    public int hashCode() {
        return Objects.hash(id);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        DestroyEpicBoardInput other = (DestroyEpicBoardInput) obj;
        return Objects.equals(id, other.id);
    }

    @Override
    public String toString() {
        return "DestroyEpicBoardInput [id=" + id + "]";
    }

}
