package graphql.gitlab.model;

import java.util.Objects;

import org.eclipse.microprofile.graphql.Name;

import graphql.gitlab.GitLabInputRequest;

/**
 * Autogenerated input type of DestroyBoard
 */
@Name("DestroyBoardInput")
public class DestroyBoardInput implements GitLabInputRequest {

    /**
     * A unique identifier for the client performing the mutation.
     */
    private String clientMutationId;

    /**
     * Global ID of the board to destroy.
     */
    private BoardID id;

    public String getClientMutationId() {
        return clientMutationId;
    }

    public DestroyBoardInput setClientMutationId(String clientMutationId) {
        this.clientMutationId = clientMutationId;
        return this;
    }

    public BoardID getId() {
        return id;
    }

    public DestroyBoardInput setId(BoardID id) {
        this.id = id;
        return this;
    }

    @Override
    public int hashCode() {
        return Objects.hash(clientMutationId, id);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        DestroyBoardInput other = (DestroyBoardInput) obj;
        return Objects.equals(clientMutationId, other.clientMutationId) && Objects.equals(id, other.id);
    }

    @Override
    public String toString() {
        return "DestroyBoardInput [clientMutationId=" + clientMutationId + ", id=" + id + "]";
    }

}
