package graphql.gitlab.model;

import java.util.Objects;

import org.eclipse.microprofile.graphql.Name;

import com.fasterxml.jackson.annotation.JsonProperty;

import graphql.gitlab.GitLabInputRequest;

/**
 * Autogenerated input type of DestroyEpicBoard
 */
@Name("DestroyEpicBoardInput")
public class DestroyEpicBoardInput implements GitLabInputRequest {

    /**
     * A unique identifier for the client performing the mutation.
     */
    private String clientMutationId;

    /**
     * Global ID of the board to destroy.
     */
    private BoardsEpicBoardID id;

    public String getClientMutationId() {
        return clientMutationId;
    }

    public DestroyEpicBoardInput setClientMutationId(String clientMutationId) {
        this.clientMutationId = clientMutationId;
        return this;
    }

    public BoardsEpicBoardID getId() {
        return id;
    }

    public DestroyEpicBoardInput setId(BoardsEpicBoardID id) {
        this.id = id;
        return this;
    }

    @JsonProperty("__typename")
    public String getTypename() {
        return "DestroyEpicBoardInput";
    }

    @JsonProperty("__typename")
    public void setTypename(String type) {
        //Setter only for Jackson
        if(!"DestroyEpicBoardInput".equals(type)) {
            throw new IllegalArgumentException("Unexpected '__typename' value: " + type);
        }
    }

    @Override
    public int hashCode() {
        return Objects.hash(clientMutationId, id);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        DestroyEpicBoardInput other = (DestroyEpicBoardInput) obj;
        return Objects.equals(clientMutationId, other.clientMutationId) && Objects.equals(id, other.id);
    }

    @Override
    public String toString() {
        return "DestroyEpicBoardInput [clientMutationId=" + clientMutationId + ", id=" + id + "]";
    }

}
