package graphql.gitlab.model;

import java.util.Objects;

import org.eclipse.microprofile.graphql.Name;

/**
 * Autogenerated input type of DestroyBoard
 */
@Name("DestroyBoardInput")
public class DestroyBoardInput {

    /**
     * Global ID of the board to destroy.
     */
    private BoardID id;

    public BoardID getId() {
        return id;
    }

    public DestroyBoardInput setId(BoardID id) {
        this.id = id;
        return this;
    }

    @Override
    public int hashCode() {
        return Objects.hash(id);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        DestroyBoardInput other = (DestroyBoardInput) obj;
        return Objects.equals(id, other.id);
    }

    @Override
    public String toString() {
        return "DestroyBoardInput [id=" + id + "]";
    }

}
