package graphql.gitlab.model;

import java.util.Objects;

import org.eclipse.microprofile.graphql.Name;

/**
 * Autogenerated input type of DestroyBoardList
 */
@Name("DestroyBoardListInput")
public class DestroyBoardListInput {

    /**
     * Global ID of the list to destroy. Only label lists are accepted.
     */
    private ListID listId;

    public ListID getListId() {
        return listId;
    }

    public DestroyBoardListInput setListId(ListID listId) {
        this.listId = listId;
        return this;
    }

    @Override
    public int hashCode() {
        return Objects.hash(listId);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        DestroyBoardListInput other = (DestroyBoardListInput) obj;
        return Objects.equals(listId, other.listId);
    }

    @Override
    public String toString() {
        return "DestroyBoardListInput [listId=" + listId + "]";
    }

}
