package graphql.gitlab.model;

import java.util.Objects;

import org.eclipse.microprofile.graphql.Name;

/**
 * Autogenerated input type of DestroyNote
 */
@Name("DestroyNoteInput")
public class DestroyNoteInput {

    /**
     * Global ID of the note to destroy.
     */
    private NoteID id;

    public NoteID getId() {
        return id;
    }

    public DestroyNoteInput setId(NoteID id) {
        this.id = id;
        return this;
    }

    @Override
    public int hashCode() {
        return Objects.hash(id);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        DestroyNoteInput other = (DestroyNoteInput) obj;
        return Objects.equals(id, other.id);
    }

    @Override
    public String toString() {
        return "DestroyNoteInput [id=" + id + "]";
    }

}
