package graphql.gitlab.model;

import java.util.List;
import java.util.Objects;

import org.eclipse.microprofile.graphql.Name;

import graphql.gitlab.GitLabPayloadResponse;

/**
 * Autogenerated return type of DestroyEpicBoard.
 */
@Name("DestroyEpicBoardPayload")
public class DestroyEpicBoardPayload implements GitLabPayloadResponse {

    /**
     * A unique identifier for the client performing the mutation.
     */
    private String clientMutationId;

    /**
     * Epic board after mutation.
     */
    private EpicBoard epicBoard;

    /**
     * Errors encountered during the mutation.
     */
    private List<String> errors;

    public String getClientMutationId() {
        return clientMutationId;
    }

    public DestroyEpicBoardPayload setClientMutationId(String clientMutationId) {
        this.clientMutationId = clientMutationId;
        return this;
    }

    public EpicBoard getEpicBoard() {
        return epicBoard;
    }

    public DestroyEpicBoardPayload setEpicBoard(EpicBoard epicBoard) {
        this.epicBoard = epicBoard;
        return this;
    }

    public List<String> getErrors() {
        return errors;
    }

    public DestroyEpicBoardPayload setErrors(List<String> errors) {
        this.errors = errors;
        return this;
    }

    @Override
    public int hashCode() {
        return Objects.hash(clientMutationId, epicBoard, errors);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        DestroyEpicBoardPayload other = (DestroyEpicBoardPayload) obj;
        return Objects.equals(clientMutationId, other.clientMutationId) && Objects.equals(epicBoard, other.epicBoard) && Objects.equals(errors, other.errors);
    }

    @Override
    public String toString() {
        return "DestroyEpicBoardPayload [clientMutationId=" + clientMutationId + ", epicBoard=" + epicBoard + ", errors=" + errors + "]";
    }

}
