package graphql.gitlab.model;

import java.util.List;
import java.util.Objects;

import org.eclipse.microprofile.graphql.Name;

import graphql.gitlab.GitLabPayloadResponse;

/**
 * Autogenerated return type of EpicBoardListDestroy.
 */
@Name("EpicBoardListDestroyPayload")
public class EpicBoardListDestroyPayload implements GitLabPayloadResponse {

    /**
     * Errors encountered during execution of the mutation.
     */
    private List<String> errors;

    /**
     * Epic board list. `null` if the board was destroyed successfully.
     */
    private EpicList list;

    public List<String> getErrors() {
        return errors;
    }

    public EpicBoardListDestroyPayload setErrors(List<String> errors) {
        this.errors = errors;
        return this;
    }

    public EpicList getList() {
        return list;
    }

    public EpicBoardListDestroyPayload setList(EpicList list) {
        this.list = list;
        return this;
    }

    @Override
    public int hashCode() {
        return Objects.hash(errors, list);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        EpicBoardListDestroyPayload other = (EpicBoardListDestroyPayload) obj;
        return Objects.equals(errors, other.errors) && Objects.equals(list, other.list);
    }

    @Override
    public String toString() {
        return "EpicBoardListDestroyPayload [errors=" + errors + ", list=" + list + "]";
    }

}
