package graphql.gitlab.model;

import java.util.Objects;

import org.eclipse.microprofile.graphql.Name;

/**
 * Autogenerated input type of EpicBoardListDestroy
 */
@Name("EpicBoardListDestroyInput")
public class EpicBoardListDestroyInput {

    /**
     * Global ID of the epic board list to destroy.
     */
    private BoardsEpicListID listId;

    public BoardsEpicListID getListId() {
        return listId;
    }

    public EpicBoardListDestroyInput setListId(BoardsEpicListID listId) {
        this.listId = listId;
        return this;
    }

    @Override
    public int hashCode() {
        return Objects.hash(listId);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        EpicBoardListDestroyInput other = (EpicBoardListDestroyInput) obj;
        return Objects.equals(listId, other.listId);
    }

    @Override
    public String toString() {
        return "EpicBoardListDestroyInput [listId=" + listId + "]";
    }

}
