package graphql.gitlab.model;

import java.util.Objects;

import org.eclipse.microprofile.graphql.Name;

import com.fasterxml.jackson.annotation.JsonProperty;

import graphql.gitlab.GitLabInputRequest;

/**
 * Autogenerated input type of EpicBoardListDestroy
 */
@Name("EpicBoardListDestroyInput")
public class EpicBoardListDestroyInput implements GitLabInputRequest {

    /**
     * A unique identifier for the client performing the mutation.
     */
    private String clientMutationId;

    /**
     * Global ID of the epic board list to destroy.
     */
    private BoardsEpicListID listId;

    public String getClientMutationId() {
        return clientMutationId;
    }

    public EpicBoardListDestroyInput setClientMutationId(String clientMutationId) {
        this.clientMutationId = clientMutationId;
        return this;
    }

    public BoardsEpicListID getListId() {
        return listId;
    }

    public EpicBoardListDestroyInput setListId(BoardsEpicListID listId) {
        this.listId = listId;
        return this;
    }

    @JsonProperty("__typename")
    public String getTypename() {
        return "EpicBoardListDestroyInput";
    }

    @JsonProperty("__typename")
    public void setTypename(String type) {
        //Setter only for Jackson
        if(!"EpicBoardListDestroyInput".equals(type)) {
            throw new IllegalArgumentException("Unexpected '__typename' value: " + type);
        }
    }

    @Override
    public int hashCode() {
        return Objects.hash(clientMutationId, listId);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        EpicBoardListDestroyInput other = (EpicBoardListDestroyInput) obj;
        return Objects.equals(clientMutationId, other.clientMutationId) && Objects.equals(listId, other.listId);
    }

    @Override
    public String toString() {
        return "EpicBoardListDestroyInput [clientMutationId=" + clientMutationId + ", listId=" + listId + "]";
    }

}
