package graphql.gitlab.model;

import java.util.List;
import java.util.Objects;

import org.eclipse.microprofile.graphql.Name;

import com.fasterxml.jackson.annotation.JsonProperty;

import graphql.gitlab.GitLabPayloadResponse;

/**
 * Autogenerated return type of EpicBoardUpdate.
 */
@Name("EpicBoardUpdatePayload")
public class EpicBoardUpdatePayload implements GitLabPayloadResponse {

    /**
     * A unique identifier for the client performing the mutation.
     */
    private String clientMutationId;

    /**
     * Updated epic board.
     */
    private EpicBoard epicBoard;

    /**
     * Errors encountered during execution of the mutation.
     */
    private List<String> errors;

    public String getClientMutationId() {
        return clientMutationId;
    }

    public EpicBoardUpdatePayload setClientMutationId(String clientMutationId) {
        this.clientMutationId = clientMutationId;
        return this;
    }

    public EpicBoard getEpicBoard() {
        return epicBoard;
    }

    public EpicBoardUpdatePayload setEpicBoard(EpicBoard epicBoard) {
        this.epicBoard = epicBoard;
        return this;
    }

    public List<String> getErrors() {
        return errors;
    }

    public EpicBoardUpdatePayload setErrors(List<String> errors) {
        this.errors = errors;
        return this;
    }

    @JsonProperty("__typename")
    public String getTypename() {
        return "EpicBoardUpdatePayload";
    }

    @JsonProperty("__typename")
    public void setTypename(String type) {
        //Setter only for Jackson
        if(!"EpicBoardUpdatePayload".equals(type)) {
            throw new IllegalArgumentException("Unexpected '__typename' value: " + type);
        }
    }

    @Override
    public int hashCode() {
        return Objects.hash(clientMutationId, epicBoard, errors);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        EpicBoardUpdatePayload other = (EpicBoardUpdatePayload) obj;
        return Objects.equals(clientMutationId, other.clientMutationId) && Objects.equals(epicBoard, other.epicBoard) && Objects.equals(errors, other.errors);
    }

    @Override
    public String toString() {
        return "EpicBoardUpdatePayload [clientMutationId=" + clientMutationId + ", epicBoard=" + epicBoard + ", errors=" + errors + "]";
    }

}
