package graphql.gitlab.model;

import java.util.Objects;

import org.eclipse.microprofile.graphql.Name;

/**
 * Autogenerated input type of EpicBoardListCreate
 */
@Name("EpicBoardListCreateInput")
public class EpicBoardListCreateInput {

    /**
     * Create the backlog list.
     */
    private Boolean backlog;

    /**
     * Global ID of an existing label.
     */
    private LabelID labelId;

    /**
     * Global ID of the issue board to mutate.
     */
    private BoardsEpicBoardID boardId;

    public Boolean getBacklog() {
        return backlog;
    }

    public EpicBoardListCreateInput setBacklog(Boolean backlog) {
        this.backlog = backlog;
        return this;
    }

    public LabelID getLabelId() {
        return labelId;
    }

    public EpicBoardListCreateInput setLabelId(LabelID labelId) {
        this.labelId = labelId;
        return this;
    }

    public BoardsEpicBoardID getBoardId() {
        return boardId;
    }

    public EpicBoardListCreateInput setBoardId(BoardsEpicBoardID boardId) {
        this.boardId = boardId;
        return this;
    }

    @Override
    public int hashCode() {
        return Objects.hash(backlog, labelId, boardId);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        EpicBoardListCreateInput other = (EpicBoardListCreateInput) obj;
        return Objects.equals(backlog, other.backlog) && Objects.equals(labelId, other.labelId) && Objects.equals(boardId, other.boardId);
    }

    @Override
    public String toString() {
        return "EpicBoardListCreateInput [backlog=" + backlog + ", labelId=" + labelId + ", boardId=" + boardId + "]";
    }

}
