package graphql.gitlab.model;

import java.util.List;
import java.util.Objects;

import org.eclipse.microprofile.graphql.Name;

import graphql.gitlab.GitLabInputRequest;

/**
 * Autogenerated input type of MergeRequestSetLabels
 */
@Name("MergeRequestSetLabelsInput")
public class MergeRequestSetLabelsInput implements GitLabInputRequest {

    /**
     * A unique identifier for the client performing the mutation.
     */
    private String clientMutationId;

    /**
     * Project the merge request to mutate is in.
     */
    private String projectPath;

    /**
     * IID of the merge request to mutate.
     */
    private String iid;

    /**
     * Label IDs to set. Replaces existing labels by default.
     */
    private List<LabelID> labelIds;

    /**
     * Changes the operation mode. Defaults to REPLACE.
     */
    private MutationOperationMode operationMode;

    public String getClientMutationId() {
        return clientMutationId;
    }

    public MergeRequestSetLabelsInput setClientMutationId(String clientMutationId) {
        this.clientMutationId = clientMutationId;
        return this;
    }

    public String getProjectPath() {
        return projectPath;
    }

    public MergeRequestSetLabelsInput setProjectPath(String projectPath) {
        this.projectPath = projectPath;
        return this;
    }

    public String getIid() {
        return iid;
    }

    public MergeRequestSetLabelsInput setIid(String iid) {
        this.iid = iid;
        return this;
    }

    public List<LabelID> getLabelIds() {
        return labelIds;
    }

    public MergeRequestSetLabelsInput setLabelIds(List<LabelID> labelIds) {
        this.labelIds = labelIds;
        return this;
    }

    public MutationOperationMode getOperationMode() {
        return operationMode;
    }

    public MergeRequestSetLabelsInput setOperationMode(MutationOperationMode operationMode) {
        this.operationMode = operationMode;
        return this;
    }

    @Override
    public int hashCode() {
        return Objects.hash(clientMutationId, projectPath, iid, labelIds, operationMode);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        MergeRequestSetLabelsInput other = (MergeRequestSetLabelsInput) obj;
        return Objects.equals(clientMutationId, other.clientMutationId) && Objects.equals(projectPath, other.projectPath) && Objects.equals(iid, other.iid) && Objects.equals(labelIds, other.labelIds) && Objects.equals(operationMode, other.operationMode);
    }

    @Override
    public String toString() {
        return "MergeRequestSetLabelsInput [clientMutationId=" + clientMutationId + ", projectPath=" + projectPath + ", iid=" + iid + ", labelIds=" + labelIds + ", operationMode=" + operationMode + "]";
    }

}
