package graphql.gitlab.model;

import java.util.List;
import java.util.Objects;

import org.eclipse.microprofile.graphql.Name;

import graphql.gitlab.GitLabPayloadResponse;

/**
 * Autogenerated return type of MergeRequestSetLabels.
 */
@Name("MergeRequestSetLabelsPayload")
public class MergeRequestSetLabelsPayload implements GitLabPayloadResponse {

    /**
     * A unique identifier for the client performing the mutation.
     */
    private String clientMutationId;

    /**
     * Errors encountered during the mutation.
     */
    private List<String> errors;

    /**
     * Merge request after mutation.
     */
    private MergeRequest mergeRequest;

    public String getClientMutationId() {
        return clientMutationId;
    }

    public MergeRequestSetLabelsPayload setClientMutationId(String clientMutationId) {
        this.clientMutationId = clientMutationId;
        return this;
    }

    public List<String> getErrors() {
        return errors;
    }

    public MergeRequestSetLabelsPayload setErrors(List<String> errors) {
        this.errors = errors;
        return this;
    }

    public MergeRequest getMergeRequest() {
        return mergeRequest;
    }

    public MergeRequestSetLabelsPayload setMergeRequest(MergeRequest mergeRequest) {
        this.mergeRequest = mergeRequest;
        return this;
    }

    @Override
    public int hashCode() {
        return Objects.hash(clientMutationId, errors, mergeRequest);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        MergeRequestSetLabelsPayload other = (MergeRequestSetLabelsPayload) obj;
        return Objects.equals(clientMutationId, other.clientMutationId) && Objects.equals(errors, other.errors) && Objects.equals(mergeRequest, other.mergeRequest);
    }

    @Override
    public String toString() {
        return "MergeRequestSetLabelsPayload [clientMutationId=" + clientMutationId + ", errors=" + errors + ", mergeRequest=" + mergeRequest + "]";
    }

}
