package graphql.gitlab.model;

import java.util.Objects;

import org.eclipse.microprofile.graphql.Name;

import graphql.gitlab.GitLabInputRequest;

/**
 * Autogenerated input type of TodoMarkDone
 */
@Name("TodoMarkDoneInput")
public class TodoMarkDoneInput implements GitLabInputRequest {

    /**
     * A unique identifier for the client performing the mutation.
     */
    private String clientMutationId;

    /**
     * Global ID of the to-do item to mark as done.
     */
    private TodoID id;

    public String getClientMutationId() {
        return clientMutationId;
    }

    public TodoMarkDoneInput setClientMutationId(String clientMutationId) {
        this.clientMutationId = clientMutationId;
        return this;
    }

    public TodoID getId() {
        return id;
    }

    public TodoMarkDoneInput setId(TodoID id) {
        this.id = id;
        return this;
    }

    @Override
    public int hashCode() {
        return Objects.hash(clientMutationId, id);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        TodoMarkDoneInput other = (TodoMarkDoneInput) obj;
        return Objects.equals(clientMutationId, other.clientMutationId) && Objects.equals(id, other.id);
    }

    @Override
    public String toString() {
        return "TodoMarkDoneInput [clientMutationId=" + clientMutationId + ", id=" + id + "]";
    }

}
