package graphql.gitlab.model;

import java.util.List;
import java.util.Objects;

import org.eclipse.microprofile.graphql.Name;

import graphql.gitlab.GitLabPayloadResponse;

/**
 * Autogenerated return type of TodoMarkDone.
 */
@Name("TodoMarkDonePayload")
public class TodoMarkDonePayload implements GitLabPayloadResponse {

    /**
     * A unique identifier for the client performing the mutation.
     */
    private String clientMutationId;

    /**
     * Errors encountered during the mutation.
     */
    private List<String> errors;

    /**
     * Requested to-do item.
     */
    private Todo todo;

    public String getClientMutationId() {
        return clientMutationId;
    }

    public TodoMarkDonePayload setClientMutationId(String clientMutationId) {
        this.clientMutationId = clientMutationId;
        return this;
    }

    public List<String> getErrors() {
        return errors;
    }

    public TodoMarkDonePayload setErrors(List<String> errors) {
        this.errors = errors;
        return this;
    }

    public Todo getTodo() {
        return todo;
    }

    public TodoMarkDonePayload setTodo(Todo todo) {
        this.todo = todo;
        return this;
    }

    @Override
    public int hashCode() {
        return Objects.hash(clientMutationId, errors, todo);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        TodoMarkDonePayload other = (TodoMarkDonePayload) obj;
        return Objects.equals(clientMutationId, other.clientMutationId) && Objects.equals(errors, other.errors) && Objects.equals(todo, other.todo);
    }

    @Override
    public String toString() {
        return "TodoMarkDonePayload [clientMutationId=" + clientMutationId + ", errors=" + errors + ", todo=" + todo + "]";
    }

}
