package graphql.gitlab.model;

import java.util.Objects;

import org.eclipse.microprofile.graphql.Name;

import com.fasterxml.jackson.annotation.JsonProperty;

import graphql.gitlab.GitLabInputRequest;

/**
 * Autogenerated input type of UpdateEpicBoardList
 */
@Name("UpdateEpicBoardListInput")
public class UpdateEpicBoardListInput implements GitLabInputRequest {

    /**
     * A unique identifier for the client performing the mutation.
     */
    private String clientMutationId;

    /**
     * Position of list within the board.
     */
    private Integer position;

    /**
     * Indicates if the list is collapsed for the user.
     */
    private Boolean collapsed;

    /**
     * Global ID of the epic list.
     */
    private BoardsEpicListID listId;

    public String getClientMutationId() {
        return clientMutationId;
    }

    public UpdateEpicBoardListInput setClientMutationId(String clientMutationId) {
        this.clientMutationId = clientMutationId;
        return this;
    }

    public Integer getPosition() {
        return position;
    }

    public UpdateEpicBoardListInput setPosition(Integer position) {
        this.position = position;
        return this;
    }

    public Boolean getCollapsed() {
        return collapsed;
    }

    public UpdateEpicBoardListInput setCollapsed(Boolean collapsed) {
        this.collapsed = collapsed;
        return this;
    }

    public BoardsEpicListID getListId() {
        return listId;
    }

    public UpdateEpicBoardListInput setListId(BoardsEpicListID listId) {
        this.listId = listId;
        return this;
    }

    @JsonProperty("__typename")
    public String getTypename() {
        return "UpdateEpicBoardListInput";
    }

    @JsonProperty("__typename")
    public void setTypename(String type) {
        //Setter only for Jackson
        if(!"UpdateEpicBoardListInput".equals(type)) {
            throw new IllegalArgumentException("Unexpected '__typename' value: " + type);
        }
    }

    @Override
    public int hashCode() {
        return Objects.hash(clientMutationId, position, collapsed, listId);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        UpdateEpicBoardListInput other = (UpdateEpicBoardListInput) obj;
        return Objects.equals(clientMutationId, other.clientMutationId) && Objects.equals(position, other.position) && Objects.equals(collapsed, other.collapsed) && Objects.equals(listId, other.listId);
    }

    @Override
    public String toString() {
        return "UpdateEpicBoardListInput [clientMutationId=" + clientMutationId + ", position=" + position + ", collapsed=" + collapsed + ", listId=" + listId + "]";
    }

}
