package graphql.gitlab.model;

import java.util.List;
import java.util.Objects;

import org.eclipse.microprofile.graphql.Name;

import com.fasterxml.jackson.annotation.JsonProperty;

import graphql.gitlab.GitLabPayloadResponse;

/**
 * Autogenerated return type of UpdateBoard.
 */
@Name("UpdateBoardPayload")
public class UpdateBoardPayload implements GitLabPayloadResponse {

    /**
     * Board after mutation.
     */
    private Board board;

    /**
     * A unique identifier for the client performing the mutation.
     */
    private String clientMutationId;

    /**
     * Errors encountered during execution of the mutation.
     */
    private List<String> errors;

    public Board getBoard() {
        return board;
    }

    public UpdateBoardPayload setBoard(Board board) {
        this.board = board;
        return this;
    }

    public String getClientMutationId() {
        return clientMutationId;
    }

    public UpdateBoardPayload setClientMutationId(String clientMutationId) {
        this.clientMutationId = clientMutationId;
        return this;
    }

    public List<String> getErrors() {
        return errors;
    }

    public UpdateBoardPayload setErrors(List<String> errors) {
        this.errors = errors;
        return this;
    }

    @JsonProperty("__typename")
    public String getTypename() {
        return "UpdateBoardPayload";
    }

    @JsonProperty("__typename")
    public void setTypename(String type) {
        //Setter only for Jackson
        if(!"UpdateBoardPayload".equals(type)) {
            throw new IllegalArgumentException("Unexpected '__typename' value: " + type);
        }
    }

    @Override
    public int hashCode() {
        return Objects.hash(board, clientMutationId, errors);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        UpdateBoardPayload other = (UpdateBoardPayload) obj;
        return Objects.equals(board, other.board) && Objects.equals(clientMutationId, other.clientMutationId) && Objects.equals(errors, other.errors);
    }

    @Override
    public String toString() {
        return "UpdateBoardPayload [board=" + board + ", clientMutationId=" + clientMutationId + ", errors=" + errors + "]";
    }

}
