package graphql.gitlab.model;

import java.util.Objects;

import org.eclipse.microprofile.graphql.Name;

/**
 * Autogenerated input type of UpdateEpicBoardList
 */
@Name("UpdateEpicBoardListInput")
public class UpdateEpicBoardListInput {

    /**
     * Position of list within the board.
     */
    private Integer position;

    /**
     * Indicates if the list is collapsed for the user.
     */
    private Boolean collapsed;

    /**
     * Global ID of the epic list.
     */
    private BoardsEpicListID listId;

    public Integer getPosition() {
        return position;
    }

    public UpdateEpicBoardListInput setPosition(Integer position) {
        this.position = position;
        return this;
    }

    public Boolean getCollapsed() {
        return collapsed;
    }

    public UpdateEpicBoardListInput setCollapsed(Boolean collapsed) {
        this.collapsed = collapsed;
        return this;
    }

    public BoardsEpicListID getListId() {
        return listId;
    }

    public UpdateEpicBoardListInput setListId(BoardsEpicListID listId) {
        this.listId = listId;
        return this;
    }

    @Override
    public int hashCode() {
        return Objects.hash(position, collapsed, listId);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        UpdateEpicBoardListInput other = (UpdateEpicBoardListInput) obj;
        return Objects.equals(position, other.position) && Objects.equals(collapsed, other.collapsed) && Objects.equals(listId, other.listId);
    }

    @Override
    public String toString() {
        return "UpdateEpicBoardListInput [position=" + position + ", collapsed=" + collapsed + ", listId=" + listId + "]";
    }

}
