package graphql.gitlab.model;

import java.util.Objects;

import org.eclipse.microprofile.graphql.Name;

/**
 * Autogenerated input type of WorkItemUpdate
 */
@Name("WorkItemUpdateInput")
public class WorkItemUpdateInput {

    /**
     * Input for assignees widget.
     */
    private WorkItemWidgetAssigneesInput assigneesWidget;
    /**
     * Input for description widget.
     */
    private WorkItemWidgetDescriptionInput descriptionWidget;
    /**
     * Input for hierarchy widget.
     */
    private WorkItemWidgetHierarchyUpdateInput hierarchyWidget;
    /**
     * Global ID of the work item.
     */
    private WorkItemID id;
    /**
     * Input for labels widget.
     */
    private WorkItemWidgetLabelsUpdateInput labelsWidget;
    /**
     * Input for start and due date widget.
     */
    private WorkItemWidgetStartAndDueDateUpdateInput startAndDueDateWidget;
    /**
     * Close or reopen a work item.
     */
    private WorkItemStateEvent stateEvent;
    /**
     * Title of the work item.
     */
    private String title;

    public WorkItemWidgetAssigneesInput getAssigneesWidget() {
        return assigneesWidget;
    }

    public WorkItemUpdateInput setAssigneesWidget(WorkItemWidgetAssigneesInput assigneesWidget) {
        this.assigneesWidget = assigneesWidget;
        return this;
    }

    public WorkItemWidgetDescriptionInput getDescriptionWidget() {
        return descriptionWidget;
    }

    public WorkItemUpdateInput setDescriptionWidget(WorkItemWidgetDescriptionInput descriptionWidget) {
        this.descriptionWidget = descriptionWidget;
        return this;
    }

    public WorkItemWidgetHierarchyUpdateInput getHierarchyWidget() {
        return hierarchyWidget;
    }

    public WorkItemUpdateInput setHierarchyWidget(WorkItemWidgetHierarchyUpdateInput hierarchyWidget) {
        this.hierarchyWidget = hierarchyWidget;
        return this;
    }

    public WorkItemID getId() {
        return id;
    }

    public WorkItemUpdateInput setId(WorkItemID id) {
        this.id = id;
        return this;
    }

    public WorkItemWidgetLabelsUpdateInput getLabelsWidget() {
        return labelsWidget;
    }

    public WorkItemUpdateInput setLabelsWidget(WorkItemWidgetLabelsUpdateInput labelsWidget) {
        this.labelsWidget = labelsWidget;
        return this;
    }

    public WorkItemWidgetStartAndDueDateUpdateInput getStartAndDueDateWidget() {
        return startAndDueDateWidget;
    }

    public WorkItemUpdateInput setStartAndDueDateWidget(WorkItemWidgetStartAndDueDateUpdateInput startAndDueDateWidget) {
        this.startAndDueDateWidget = startAndDueDateWidget;
        return this;
    }

    public WorkItemStateEvent getStateEvent() {
        return stateEvent;
    }

    public WorkItemUpdateInput setStateEvent(WorkItemStateEvent stateEvent) {
        this.stateEvent = stateEvent;
        return this;
    }

    public String getTitle() {
        return title;
    }

    public WorkItemUpdateInput setTitle(String title) {
        this.title = title;
        return this;
    }

    @Override
    public int hashCode() {
        return Objects.hash(assigneesWidget, descriptionWidget, hierarchyWidget, id, labelsWidget, startAndDueDateWidget, stateEvent, title);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        WorkItemUpdateInput other = (WorkItemUpdateInput) obj;
        return Objects.equals(assigneesWidget, other.assigneesWidget) && Objects.equals(descriptionWidget, other.descriptionWidget) && Objects.equals(hierarchyWidget, other.hierarchyWidget) && Objects.equals(id, other.id) && Objects.equals(labelsWidget, other.labelsWidget) && Objects.equals(startAndDueDateWidget, other.startAndDueDateWidget) && Objects.equals(stateEvent, other.stateEvent) && Objects.equals(title, other.title);
    }

    @Override
    public String toString() {
        return "WorkItemUpdateInput [assigneesWidget=" + assigneesWidget + ", descriptionWidget=" + descriptionWidget + ", hierarchyWidget=" + hierarchyWidget + ", id=" + id + ", labelsWidget=" + labelsWidget + ", startAndDueDateWidget=" + startAndDueDateWidget + ", stateEvent=" + stateEvent + ", title=" + title + "]";
    }

}
