package graphql.gitlab.model;

import java.util.Objects;

import org.eclipse.microprofile.graphql.Name;

/**
 * Autogenerated input type of WorkItemDelete
 */
@Name("WorkItemDeleteInput")
public class WorkItemDeleteInput {

    /**
     * Global ID of the work item.
     */
    private WorkItemID id;

    public WorkItemID getId() {
        return id;
    }

    public WorkItemDeleteInput setId(WorkItemID id) {
        this.id = id;
        return this;
    }

    @Override
    public int hashCode() {
        return Objects.hash(id);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        WorkItemDeleteInput other = (WorkItemDeleteInput) obj;
        return Objects.equals(id, other.id);
    }

    @Override
    public String toString() {
        return "WorkItemDeleteInput [id=" + id + "]";
    }

}
