package graphql.gitlab.model;

import java.util.Objects;

import org.eclipse.microprofile.graphql.Name;

/**
 * Autogenerated input type of WorkItemCreate
 */
@Name("WorkItemCreateInput")
public class WorkItemCreateInput {

    /**
     * Input for assignees widget.
     */
    private WorkItemWidgetAssigneesInput assigneesWidget;

    /**
     * Input for description widget.
     */
    private WorkItemWidgetDescriptionInput descriptionWidget;

    /**
     * Full path of the namespace(project or group) the work item is created in.
     */
    private String namespacePath;

    /**
     * Title of the work item.
     */
    private String title;

    /**
     * Global ID of a work item type.
     */
    private WorkItemsTypeID workItemTypeId;

    public WorkItemWidgetAssigneesInput getAssigneesWidget() {
        return assigneesWidget;
    }

    public WorkItemCreateInput setAssigneesWidget(WorkItemWidgetAssigneesInput assigneesWidget) {
        this.assigneesWidget = assigneesWidget;
        return this;
    }

    public WorkItemWidgetDescriptionInput getDescriptionWidget() {
        return descriptionWidget;
    }

    public WorkItemCreateInput setDescriptionWidget(WorkItemWidgetDescriptionInput descriptionWidget) {
        this.descriptionWidget = descriptionWidget;
        return this;
    }

    public String getNamespacePath() {
        return namespacePath;
    }

    public WorkItemCreateInput setNamespacePath(String namespacePath) {
        this.namespacePath = namespacePath;
        return this;
    }

    public String getTitle() {
        return title;
    }

    public WorkItemCreateInput setTitle(String title) {
        this.title = title;
        return this;
    }

    public WorkItemsTypeID getWorkItemTypeId() {
        return workItemTypeId;
    }

    public WorkItemCreateInput setWorkItemTypeId(WorkItemsTypeID workItemTypeId) {
        this.workItemTypeId = workItemTypeId;
        return this;
    }

    @Override
    public int hashCode() {
        return Objects.hash(assigneesWidget, descriptionWidget, namespacePath, title, workItemTypeId);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        WorkItemCreateInput other = (WorkItemCreateInput) obj;
        return Objects.equals(assigneesWidget, other.assigneesWidget) && Objects.equals(descriptionWidget, other.descriptionWidget) && Objects.equals(namespacePath, other.namespacePath) && Objects.equals(title, other.title) && Objects.equals(workItemTypeId, other.workItemTypeId);
    }

    @Override
    public String toString() {
        return "WorkItemCreateInput [assigneesWidget=" + assigneesWidget + ", descriptionWidget=" + descriptionWidget + ", namespacePath=" + namespacePath + ", title=" + title + ", workItemTypeId=" + workItemTypeId + "]";
    }

}
