package graphql.gitlab.model;

import java.util.Objects;

import org.eclipse.microprofile.graphql.Name;

import graphql.gitlab.GitLabInputRequest;

/**
 * Autogenerated input type of WorkItemDelete
 */
@Name("WorkItemDeleteInput")
public class WorkItemDeleteInput implements GitLabInputRequest {

    /**
     * A unique identifier for the client performing the mutation.
     */
    private String clientMutationId;

    /**
     * Global ID of the work item.
     */
    private WorkItemID id;

    public String getClientMutationId() {
        return clientMutationId;
    }

    public WorkItemDeleteInput setClientMutationId(String clientMutationId) {
        this.clientMutationId = clientMutationId;
        return this;
    }

    public WorkItemID getId() {
        return id;
    }

    public WorkItemDeleteInput setId(WorkItemID id) {
        this.id = id;
        return this;
    }

    @Override
    public int hashCode() {
        return Objects.hash(clientMutationId, id);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        WorkItemDeleteInput other = (WorkItemDeleteInput) obj;
        return Objects.equals(clientMutationId, other.clientMutationId) && Objects.equals(id, other.id);
    }

    @Override
    public String toString() {
        return "WorkItemDeleteInput [clientMutationId=" + clientMutationId + ", id=" + id + "]";
    }

}
