package graphql.gitlab.model;

import java.util.List;
import java.util.Objects;

import org.eclipse.microprofile.graphql.Name;

import graphql.gitlab.GitLabPayloadResponse;

/**
 * Autogenerated return type of WorkItemDelete.
 */
@Name("WorkItemDeletePayload")
public class WorkItemDeletePayload implements GitLabPayloadResponse {

    /**
     * A unique identifier for the client performing the mutation.
     */
    private String clientMutationId;

    /**
     * Errors encountered during the mutation.
     */
    private List<String> errors;

    /**
     * Namespace the deleted work item belonged to.
     */
    private Namespace namespace;

    public String getClientMutationId() {
        return clientMutationId;
    }

    public WorkItemDeletePayload setClientMutationId(String clientMutationId) {
        this.clientMutationId = clientMutationId;
        return this;
    }

    public List<String> getErrors() {
        return errors;
    }

    public WorkItemDeletePayload setErrors(List<String> errors) {
        this.errors = errors;
        return this;
    }

    public Namespace getNamespace() {
        return namespace;
    }

    public WorkItemDeletePayload setNamespace(Namespace namespace) {
        this.namespace = namespace;
        return this;
    }

    @Override
    public int hashCode() {
        return Objects.hash(clientMutationId, errors, namespace);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        WorkItemDeletePayload other = (WorkItemDeletePayload) obj;
        return Objects.equals(clientMutationId, other.clientMutationId) && Objects.equals(errors, other.errors) && Objects.equals(namespace, other.namespace);
    }

    @Override
    public String toString() {
        return "WorkItemDeletePayload [clientMutationId=" + clientMutationId + ", errors=" + errors + ", namespace=" + namespace + "]";
    }

}
