package graphql.gitlab.model;

import java.util.List;
import java.util.Objects;

import org.eclipse.microprofile.graphql.Name;

import graphql.gitlab.GitLabPayloadResponse;

/**
 * Autogenerated return type of WorkItemRemoveLinkedItems.
 */
@Name("WorkItemRemoveLinkedItemsPayload")
public class WorkItemRemoveLinkedItemsPayload implements GitLabPayloadResponse {

    /**
     * A unique identifier for the client performing the mutation.
     */
    private String clientMutationId;

    /**
     * Errors encountered during execution of the mutation.
     */
    private List<String> errors;

    /**
     * Linked items update result message.
     */
    private String message;

    /**
     * Updated work item.
     */
    private WorkItem workItem;

    public String getClientMutationId() {
        return clientMutationId;
    }

    public WorkItemRemoveLinkedItemsPayload setClientMutationId(String clientMutationId) {
        this.clientMutationId = clientMutationId;
        return this;
    }

    public List<String> getErrors() {
        return errors;
    }

    public WorkItemRemoveLinkedItemsPayload setErrors(List<String> errors) {
        this.errors = errors;
        return this;
    }

    public String getMessage() {
        return message;
    }

    public WorkItemRemoveLinkedItemsPayload setMessage(String message) {
        this.message = message;
        return this;
    }

    public WorkItem getWorkItem() {
        return workItem;
    }

    public WorkItemRemoveLinkedItemsPayload setWorkItem(WorkItem workItem) {
        this.workItem = workItem;
        return this;
    }

    @Override
    public int hashCode() {
        return Objects.hash(clientMutationId, errors, message, workItem);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        WorkItemRemoveLinkedItemsPayload other = (WorkItemRemoveLinkedItemsPayload) obj;
        return Objects.equals(clientMutationId, other.clientMutationId) && Objects.equals(errors, other.errors) && Objects.equals(message, other.message) && Objects.equals(workItem, other.workItem);
    }

    @Override
    public String toString() {
        return "WorkItemRemoveLinkedItemsPayload [clientMutationId=" + clientMutationId + ", errors=" + errors + ", message=" + message + ", workItem=" + workItem + "]";
    }

}
