package graphql.gitlab.model;

import java.util.List;
import java.util.Objects;

import org.eclipse.microprofile.graphql.Name;

import com.fasterxml.jackson.annotation.JsonProperty;

import graphql.gitlab.GitLabPayloadResponse;

/**
 * Autogenerated return type of WorkItemAddLinkedItems.
 */
@Name("WorkItemAddLinkedItemsPayload")
public class WorkItemAddLinkedItemsPayload implements GitLabPayloadResponse {

    /**
     * A unique identifier for the client performing the mutation.
     */
    private String clientMutationId;

    /**
     * Errors encountered during execution of the mutation.
     */
    private List<String> errors;

    /**
     * Linked items update result message.
     */
    private String message;

    /**
     * Updated work item.
     */
    private WorkItem workItem;

    public String getClientMutationId() {
        return clientMutationId;
    }

    public WorkItemAddLinkedItemsPayload setClientMutationId(String clientMutationId) {
        this.clientMutationId = clientMutationId;
        return this;
    }

    public List<String> getErrors() {
        return errors;
    }

    public WorkItemAddLinkedItemsPayload setErrors(List<String> errors) {
        this.errors = errors;
        return this;
    }

    public String getMessage() {
        return message;
    }

    public WorkItemAddLinkedItemsPayload setMessage(String message) {
        this.message = message;
        return this;
    }

    public WorkItem getWorkItem() {
        return workItem;
    }

    public WorkItemAddLinkedItemsPayload setWorkItem(WorkItem workItem) {
        this.workItem = workItem;
        return this;
    }

    @JsonProperty("__typename")
    public String getTypename() {
        return "WorkItemAddLinkedItemsPayload";
    }

    @JsonProperty("__typename")
    public void setTypename(String type) {
        //Setter only for Jackson
        if(!"WorkItemAddLinkedItemsPayload".equals(type)) {
            throw new IllegalArgumentException("Unexpected '__typename' value: " + type);
        }
    }

    @Override
    public int hashCode() {
        return Objects.hash(clientMutationId, errors, message, workItem);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        WorkItemAddLinkedItemsPayload other = (WorkItemAddLinkedItemsPayload) obj;
        return Objects.equals(clientMutationId, other.clientMutationId) && Objects.equals(errors, other.errors) && Objects.equals(message, other.message) && Objects.equals(workItem, other.workItem);
    }

    @Override
    public String toString() {
        return "WorkItemAddLinkedItemsPayload [clientMutationId=" + clientMutationId + ", errors=" + errors + ", message=" + message + ", workItem=" + workItem + "]";
    }

}
